version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data"]
      interval: 10s
      timeout: 5s
      retries: 5